# This is a basic workflow to help you get started with Actions

name: autofetch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3

      # setup python
      - name: setup python
        uses: setup-python@v4
        with:
          python-version: "3.9"

      # install required packages
      - name: install packages
        run: pip install pandas beautifulsoup4 html5lib lxml

      # run the script
      - name: fetch new data
        run: python main.py

      - name: commit and push
        run: |
          git config user.name Agos95
          git config user.email agostini.federico.95@gmail.com
          git add .
          git commit -m "autofetch_$(date +'%Y-%m-%d')"
          git push
